"""
Inquiry Config Schema
Defines the structure of an inquiry configuration file using Pydantic models.
Validates configs generated by the planning agent or created manually.
"""

from __future__ import annotations

import json
from enum import Enum
from pathlib import Path
from typing import Optional

from pydantic import BaseModel, Field, model_validator


class InquiryFormat(str, Enum):
    DEBATE = "debate"
    PANEL = "panel"


class RoundType(str, Enum):
    PARALLEL_STATEMENTS = "parallel_statements"
    PAIRED_EXCHANGE = "paired_exchange"
    MODERATOR_SYNTHESIS = "moderator_synthesis"
    PANEL_QA = "panel_qa"


class ModelChoice(str, Enum):
    SONNET = "sonnet"
    OPUS = "opus"


class PositionDirection(str, Enum):
    FOR = "for"
    AGAINST = "against"
    NEUTRAL = "neutral"


# ---------------------------------------------------------------------------
# Model name resolution
# ---------------------------------------------------------------------------

MODEL_IDS = {
    ModelChoice.SONNET: "claude-sonnet-4-6",
    ModelChoice.OPUS: "claude-opus-4-6",
}


def resolve_model(choice: ModelChoice) -> str:
    """Return the full Anthropic model ID for a ModelChoice."""
    return MODEL_IDS[choice]


# ---------------------------------------------------------------------------
# Config models
# ---------------------------------------------------------------------------

class Participant(BaseModel):
    """A single debate/panel participant (advocate)."""
    id: str = Field(description="Unique snake_case identifier, e.g. 'economist'")
    display_name: str = Field(description="Human-readable name, e.g. 'The Economist'")
    role: str = Field(description="One-line disciplinary role, e.g. 'Markets, incentives, and trade-offs'")
    system_prompt: str = Field(description="Full system prompt defining this participant's identity and methodology")
    position_direction: PositionDirection = Field(
        default=PositionDirection.NEUTRAL,
        description="Whether this participant argues for, against, or neutrally on the central question"
    )


class Pairing(BaseModel):
    """A directed pairing for paired_exchange rounds."""
    questioner: str = Field(description="Participant ID of the questioner")
    target: str = Field(description="Participant ID of the responder")
    tension: str = Field(default="", description="Description of the tension this pairing should explore")


class RequiredText(BaseModel):
    """A text that all participants must engage with in a round."""
    order: int
    text_name: str
    passage: str = Field(default="")
    core_dispute: str = Field(default="")


class RoundConfig(BaseModel):
    """Configuration for a single debate round."""
    key: str = Field(description="Unique round identifier, e.g. 'round_1', 'predebate'")
    title: str = Field(description="Display title, e.g. 'Opening Statements'")
    type: RoundType
    prompt_template: str = Field(description="Prompt template with {CURLY} and [BRACKET] placeholders")
    model: ModelChoice = Field(default=ModelChoice.SONNET)
    word_limit: int = Field(default=800)
    verify_citations: bool = Field(default=True)
    run_moderation: bool = Field(default=True)
    generate_digest: bool = Field(default=True)
    pairings: list[Pairing] = Field(default_factory=list, description="Only used for paired_exchange rounds")
    required_texts: list[RequiredText] = Field(default_factory=list, description="Texts all participants must engage with")
    reversed_speaking_order: bool = Field(default=False, description="If True, run participants in reverse order")
    use_compressed_context: bool = Field(default=False, description="If True, use context compression (summaries of other participants)")
    generate_claim_ledger: bool = Field(default=False, description="If True, generate/update the claim ledger after this round")

    # For moderator_synthesis rounds
    synthesis_prompt: str = Field(default="", description="Prompt for the moderator synthesis step")
    response_prompt: str = Field(default="", description="Prompt for participant responses to synthesis")

    # For panel_qa rounds
    user_prompt: str = Field(default="", description="The user's question (filled at runtime for panel_qa)")


class ModeratorConfig(BaseModel):
    """Configuration for the moderator agent."""
    system_prompt: str
    fact_check_prompt: str = Field(default="", description="Template for per-round fact-check/moderation")


class TemperatureSettings(BaseModel):
    participants: float = Field(default=0.75)
    moderator: float = Field(default=0.25)
    verifier: float = Field(default=0.25)
    language_tasks: float = Field(default=0.3, description="For summaries, digests, etc.")


class Settings(BaseModel):
    anti_convergence: bool = Field(default=True)
    citation_protocol: bool = Field(default=True)
    temperature: TemperatureSettings = Field(default_factory=TemperatureSettings)


class InquiryDefinition(BaseModel):
    """The inquiry itself - the question being explored."""
    title: str
    question: str
    format: InquiryFormat = Field(default=InquiryFormat.DEBATE)
    grounding_document: str = Field(default="", description="Optional anchor text content")
    grounding_document_label: str = Field(default="", description="Display label for the grounding document")
    shared_context: str = Field(default="", description="Design philosophy, rules of evidence, etc.")


class InquiryConfig(BaseModel):
    """Top-level inquiry configuration. This is what gets saved as inquiry_config.json."""
    version: str = Field(default="2.0")
    inquiry: InquiryDefinition
    participants: list[Participant] = Field(min_length=2)
    moderator: ModeratorConfig
    rounds: list[RoundConfig] = Field(min_length=1)
    settings: Settings = Field(default_factory=Settings)

    @model_validator(mode="after")
    def validate_pairings_reference_valid_participants(self) -> "InquiryConfig":
        participant_ids = {p.id for p in self.participants}
        for round_cfg in self.rounds:
            for pairing in round_cfg.pairings:
                if pairing.questioner not in participant_ids:
                    raise ValueError(f"Pairing questioner '{pairing.questioner}' not in participants")
                if pairing.target not in participant_ids:
                    raise ValueError(f"Pairing target '{pairing.target}' not in participants")
        return self

    @property
    def participant_ids(self) -> list[str]:
        """Ordered list of participant IDs."""
        return [p.id for p in self.participants]

    @property
    def participant_map(self) -> dict[str, Participant]:
        """Lookup participant by ID."""
        return {p.id: p for p in self.participants}

    def get_round(self, key: str) -> RoundConfig | None:
        """Look up a round by its key."""
        for r in self.rounds:
            if r.key == key:
                return r
        return None

    @property
    def round_keys(self) -> list[str]:
        """Ordered list of round keys."""
        return [r.key for r in self.rounds]

    def prerequisites_for(self, round_key: str) -> list[str]:
        """Return round keys that must be complete before this round can run.
        Convention: all prior rounds in the list are prerequisites."""
        keys = self.round_keys
        if round_key not in keys:
            return []
        idx = keys.index(round_key)
        return keys[:idx]


# ---------------------------------------------------------------------------
# Load / save helpers
# ---------------------------------------------------------------------------

def load_inquiry_config(path: str | Path) -> InquiryConfig:
    """Load and validate an inquiry config from a JSON file."""
    with open(path) as f:
        data = json.load(f)
    return InquiryConfig(**data)


def save_inquiry_config(config: InquiryConfig, path: str | Path) -> None:
    """Save an inquiry config to a JSON file."""
    with open(path, "w") as f:
        json.dump(config.model_dump(mode="json"), f, indent=2)
